### ISSUE TITLE
ImportError: cannot import name 'MODEL_COST_PER_1K_TOKENS' 

### ISSUE THREAD

**Issue by olimexsmart** [gpt-engineer-org/gpt-engineer#968]
```
$ gpt-engineer.exe testGPTEng/
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\gpt-engineer.exe\__main__.py", line 4, in <module>
  File "C:\Python312\Lib\site-packages\gpt_engineer\__init__.py", line 2, in <module>
    from gpt_engineer.core import (
  File "C:\Python312\Lib\site-packages\gpt_engineer\core\ai.py", line 39, in <module>
    from langchain.callbacks.openai_info import MODEL_COST_PER_1K_TOKENS
ImportError: cannot import name 'MODEL_COST_PER_1K_TOKENS' from 'langchain.callbacks.openai_info' (C:\Python312\Lib\site-packages\langchain\callbacks\openai_info.py)
```
I get this error at first setup, Python 3.12.1 on Windows 11. API key added into system-wide environment variables. Same result from Windows prompt and Git Bash. `gpte` command is not recognized.

**Comment by mistertyra01** [comment]
I have the same error.

**Comment by ATheorell** [comment]
gptengineer does not support python 3.12. It would be great if you could see if it this repeats with python 3.10 or 3.11. Something tells me that this error may relate to the langchain version.

**Comment by TheoMcCabe** [comment]
Ive fixed a similar issue in my projects. Is because of breaking changes in langchain. Ill put a fix up for this now

**Comment by olimexsmart** [comment]
I've tried the same setup on a Mac running python 3.9 and there was another python stack trace so I kinda lost interest 

Can't mess around with the Python installation on my work machine I'm sorry

**Comment by kitschpatrol** [comment]
I ran into this error on my Mac, but switching from Python 3.12 to Python 3.11 fixed it.

I was confused since the main [readme mentions Python 3.12 support](https://github.com/gpt-engineer-org/gpt-engineer?tab=readme-ov-file#install-gpt-engineer), but that must only be in reference to building from source and not the pip release?

**Comment by Merculous** [comment]
Doesn't work on 3.10.12 or 3.12.1. The pip package is what I used and I am using an environment variable for the key.

Tested on Ubuntu 22.04.3 x86_64

**Comment by ATheorell** [comment]
I believe our release cycle (->pip) is lagging behind the development here on main by quite a bit unfortunately @Merculous  . Thanks a lot for the detailed comment!

Can you make a new release @viborc ? I believe the current main version is relatively stable.

**Comment by viborc** [comment]
I believe so! I will get in touch with any questions.

**Comment by ATheorell** [comment]
Version 0.2.7 is now up on github. Would be amazing if you could report if this problem persists @Merculous . If its fixed, I'll close this issue

**Comment by Merculous** [comment]
I'm still experiencing an issue regarding 3.12.1.

I believe this is at least that version's culprit.

https://github.com/gpt-engineer-org/gpt-engineer/blob/f96a6a6f3dcaa3a0df55e2dfe1a197b8634e517b/poetry.lock#L3954

Likely fix is just to replace <3.12 with <4.0?

This is the error I get when forcing latest version.

ERROR: Ignored the following versions that require a different python version: 0.2.0 Requires-Python >=3.8.1,<3.12; 0.2.1 Requires-Python >=3.8.1,<3.12; 0.2.2 Requires-Python >=3.8.1,<3.12; 0.2.3 Requires-Python >=3.8.1,<3.12; 0.2.4 Requires-Python >=3.8.1,<3.12; 0.2.5 Requires-Python >=3.8.1,<3.12; 0.2.6 Requires-Python >=3.8.1,<3.12; 0.2.7 Requires-Python >=3.10,<3.12
ERROR: Could not find a version that satisfies the requirement gpt-engineer==0.2.7 (from versions: 0.0.1, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.1.0)
ERROR: No matching distribution found for gpt-engineer==0.2.7

If I use `pip install -U gpt-engineer` for 3.12.1, it always defaults to version 0.1.0, which is obviously not the latest.

For Python 3.11.0rc1, it installs 0.2.7.

Well, I think that the token is likely fixed, but I just realized as well this is a GPT4 tool, which I don't have access to (oops).

**Comment by ATheorell** [comment]
Thanks a lot for reporting. I believe we should simply unlock version 3.12, don't see any reason against it. 
Anyway, I would say the model cost issue is solved, so I will close this issue.

I thought everybody has gpt4 API access now by default no?
